### ISSUE TITLE
Dribbble v1 deprecated

### ISSUE THREAD

**Issue by erdemalpay** [sebabelmar/passport-dribbble#2]
![image](https://user-images.githubusercontent.com/1947630/38351154-f7e6a034-38b6-11e8-8b73-9a82b1fe5bc9.png)

https://github.com/sebabelmar/passport-dribbble/blob/master/lib/passport-dribbble/strategy.js#L74 should be updated

**Comment by karthicks** [comment]
Looks like this issue is still open, judging by this error message:

```
failed to fetch user profile (status: 401 data: {
  "message": "This version of the API is deprecated. This application must use v2: http://developer.dribbble.com/v2/"
})
    at .../node_modules/passport-dribbble/lib/passport-dribbble/strategy.js:75:28
```

**Comment by lockinmarv** [comment]
https://api.dribbble.com/v1/user doesn't work anymore. Replacing  `v1` with `v2` works again. Please update. :) cc @sebabelmar
